version: '3.7'

services:
  ci-0.35.0:
    build:
      dockerfile: './.buildkite/Dockerfile'
      context: '.'
      args:
        version: 0.35.0

  ci-0.34.0:
     build:
       dockerfile: './buildkite/Dockerfile'
       context: '.'
       args:
         version: 0.34.0
  ci-0.33.0:
     build:
       dockerfile: './buildkite/Dockerfile'
       context: '.'
       args:
         version: 0.33.0
