version: '3.7'

services:
  ci-0.35.1:
    build:
      dockerfile: './.buildkite/Dockerfile'
      context: '.'
      args:
        VERSION: 0.35.1

  ci-latest:
    build:
      dockerfile: './.buildkite/Dockerfile'
      context: '.'
      args:
        VERSION: latest
